# Generated by Django 3.0.3 on 2020-02-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversationList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='此条对话的id，自增')),
                ('userId', models.IntegerField(null=True, verbose_name='用户id，对话双方')),
                ('expertId', models.IntegerField(null=True, verbose_name='专家id，对话双方')),
                ('content', models.CharField(max_length=1024, verbose_name='对话内容')),
            ],
        ),
        migrations.CreateModel(
            name='experts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='专家id，自增')),
                ('name', models.CharField(max_length=20, verbose_name='专家姓名')),
                ('gender', models.CharField(max_length=4, verbose_name='专家性别')),
                ('keywords', models.CharField(max_length=40, verbose_name='主治类别，骨科之类')),
            ],
        ),
    ]
