# Generated by Django 3.0.3 on 2020-02-17 04:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('h', '0002_conversationlist_experts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ban',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键，自增')),
                ('title', models.CharField(max_length=128, null=True, unique=True, verbose_name='病名，唯一')),
                ('content', models.CharField(max_length=2048, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键，自增')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='文章名称')),
                ('content', models.CharField(max_length=3072, verbose_name='文章内容')),
                ('pub_time', models.DateField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('click_num', models.IntegerField(null=True, verbose_name='点击量')),
                ('pub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='h.user')),
            ],
        ),
    ]
