# Generated by Django 3.0.3 on 2020-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('h', '0004_vercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='用户账号，唯一'),
        ),
        migrations.AlterField(
            model_name='vercode',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='发送验证码的邮箱'),
        ),
    ]
